# Railway Railpack Configuration
# Railpack = auto-builder moderno (reemplaza Nixpacks deprecated)

[build]
builder = "RAILPACK"
buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health/connections"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Variables de entorno (Railway las detecta automáticamente)
[env]
PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
